### ISSUE TITLE
Improve "video embed" abstraction

### ISSUE THREAD

**Issue by lukasbestle** [k-next/embed#1]
Currently, the [Vimeo class extends the YouTube class](https://github.com/k-next/embed/blob/master/src/Embed/Vimeo.php#L14). I think we should make a "Video" class and make both of them extend that one.

Advantage: If YouTube no longer exists some day, the semantics still make sense.

**Comment by bastianallgeier** [comment]
Very good idea! We could actually even make the video class smart enough to detect either youtube or vimeo urls.
